"""init

Revision ID: 24d180ec1f20
Revises: 
Create Date: 2024-07-08 13:16:45.007644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24d180ec1f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yelp_business_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.String(length=5), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('yelp_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('yelp_business_id'),
    sa.UniqueConstraint('yelp_url'),
    schema='restaurant'
    )
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('monday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('tuesday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('wednesday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('thursday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('friday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('saturday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('sunday', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id'),
    schema='restaurant'
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_url', sa.String(length=150), nullable=False),
    sa.Column('popular_dishes', postgresql.ARRAY(sa.String(length=150)), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_url'),
    sa.UniqueConstraint('restaurant_id'),
    schema='restaurant'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu', schema='restaurant')
    op.drop_table('business_hours', schema='restaurant')
    op.drop_table('restaurant', schema='restaurant')
    # ### end Alembic commands ###
